[package]
name = "simple_terminal"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
anyhow = "1.0.71"
omegle-rs = {path = "../.."}